# Generated by Django 6.0.3 on 2026-03-24 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_material_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='seccion',
            field=models.CharField(choices=[('general', 'Generales'), ('menor', 'Sección Menor'), ('media', 'Sección Media'), ('intermedia', 'Sección Intermedia'), ('mayor', 'Sección Mayor')], default='general', max_length=20),
        ),
    ]
