# Generated by Django 6.0.3 on 2026-03-24 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_programa'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.programa'),
        ),
    ]
