# Generated by Django 6.0.3 on 2026-03-24 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_material_programa'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='seccion',
            field=models.CharField(choices=[('menor', 'Sección Menor'), ('media', 'Sección Media'), ('intermedia', 'Sección Intermedia'), ('mayor', 'Sección Mayor'), ('dirigentes', 'Formación de Dirigentes')], default='mayor', max_length=20),
            preserve_default=False,
        ),
    ]
