# Generated by Django 6.0.3 on 2026-03-24 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_programa_seccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaPrograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='core.programa')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
    ]
