# Generated by Django 6.0.3 on 2026-03-24 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_material_area_programa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='area_programa',
        ),
        migrations.RemoveField(
            model_name='material',
            name='programa',
        ),
        migrations.AddField(
            model_name='material',
            name='areas_programa',
            field=models.ManyToManyField(blank=True, to='core.areaprograma'),
        ),
        migrations.AddField(
            model_name='material',
            name='programas',
            field=models.ManyToManyField(blank=True, to='core.programa'),
        ),
    ]
