# Generated by Django 6.0.3 on 2026-03-24 05:52

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_material_area_programa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='descripcion',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Descripción'),
        ),
    ]
