# Generated by Django 6.0.3 on 2026-03-24 06:09

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_programa_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaprograma',
            name='descripcion',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Descripción'),
        ),
    ]
