# Generated by Django 6.0.3 on 2026-03-24 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_pregunta_opcionrespuesta_trivia_pregunta_trivia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trivia',
            name='programa',
        ),
    ]
