# Generated by Django 6.0.3 on 2026-03-24 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_trivia_programa'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoTrivia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('puntaje', models.PositiveIntegerField()),
                ('total_preguntas', models.PositiveIntegerField()),
                ('porcentaje', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('trivia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='core.trivia')),
            ],
            options={
                'ordering': ['-porcentaje', '-puntaje', 'fecha'],
            },
        ),
    ]
