# Generated by Django 6.0.3 on 2026-03-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_resultadotrivia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultadotrivia',
            options={'ordering': ['-porcentaje', '-puntaje', 'tiempo_total_segundos', 'fecha']},
        ),
        migrations.AddField(
            model_name='resultadotrivia',
            name='tiempo_total_segundos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
