# Generated by Django 6.0.3 on 2026-03-24 22:46

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_noticia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContenidoInicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_quienes_somos', models.CharField(default='Quiénes somos', max_length=200)),
                ('texto_quienes_somos', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Texto quiénes somos')),
                ('imagen_quienes_somos', models.ImageField(blank=True, null=True, upload_to='inicio/')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Contenido de inicio',
                'verbose_name_plural': 'Contenido de inicio',
            },
        ),
    ]
