# Generated by Django 6.0.3 on 2026-03-24 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_contenidoinicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteresCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('seccion', models.CharField(blank=True, max_length=100)),
                ('curso_interes', models.CharField(max_length=200)),
                ('detalle', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Interés en curso',
                'verbose_name_plural': 'Intereses en cursos',
                'ordering': ['-fecha'],
            },
        ),
    ]
