# Generated by Django 6.0.3 on 2026-03-25 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_interescurso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areaprograma',
            options={'ordering': ['orden', 'id'], 'verbose_name': 'Área de programa', 'verbose_name_plural': 'Áreas de programa'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['titulo'], 'verbose_name': 'Material', 'verbose_name_plural': 'Materiales'},
        ),
        migrations.AlterModelOptions(
            name='opcionrespuesta',
            options={'verbose_name': 'Opción de respuesta', 'verbose_name_plural': 'Opciones de respuesta'},
        ),
        migrations.AlterModelOptions(
            name='pregunta',
            options={'ordering': ['orden', 'id'], 'verbose_name': 'Pregunta', 'verbose_name_plural': 'Preguntas'},
        ),
        migrations.AlterModelOptions(
            name='programa',
            options={'ordering': ['seccion', 'nombre'], 'verbose_name': 'Programa', 'verbose_name_plural': 'Programas'},
        ),
        migrations.AlterModelOptions(
            name='resultadotrivia',
            options={'ordering': ['-porcentaje', '-puntaje', 'tiempo_total_segundos', 'fecha'], 'verbose_name': 'Resultado de trivia', 'verbose_name_plural': 'Resultados de trivia'},
        ),
        migrations.AlterModelOptions(
            name='trivia',
            options={'ordering': ['titulo'], 'verbose_name': 'Trivia', 'verbose_name_plural': 'Trivias'},
        ),
    ]
