# Generated by Django 6.0.3 on 2026-03-25 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_areaprograma_options_alter_material_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenaPasos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('tiempo_limite_segundos', models.PositiveIntegerField(default=60)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ordena los pasos',
                'verbose_name_plural': 'Ordena los pasos',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='PasoOrdenaPasos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=300)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='ordena_pasos/')),
                ('orden_correcto', models.PositiveIntegerField(default=1)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos', to='core.ordenapasos')),
            ],
            options={
                'verbose_name': 'Paso de ordena los pasos',
                'verbose_name_plural': 'Pasos de ordena los pasos',
                'ordering': ['orden_correcto', 'id'],
            },
        ),
    ]
