# Generated by Django 6.0.3 on 2026-03-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_ordenapasos_pasoordenapasos'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenidoinicio',
            name='subtitulo_inicio',
            field=models.TextField(default='Plataforma de formación y crecimiento scout'),
        ),
        migrations.AddField(
            model_name='contenidoinicio',
            name='subtitulo_quiero_aprender',
            field=models.TextField(default='Este espacio permite proponer cursos, talleres o temas de formación que te gustaría realizar. La idea es conocer mejor los intereses de la comunidad y organizar propuestas útiles y concretas.'),
        ),
        migrations.AddField(
            model_name='contenidoinicio',
            name='titulo_inicio',
            field=models.CharField(default='Escuela de Formación Scout', max_length=200),
        ),
        migrations.AddField(
            model_name='contenidoinicio',
            name='titulo_quiero_aprender',
            field=models.CharField(default='Quiero aprender', max_length=200),
        ),
    ]
