# Generated by Django 6.0.3 on 2026-03-26 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_contenidoinicio_subtitulo_inicio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordenapasos',
            options={'ordering': ['titulo'], 'verbose_name': 'Tema de ordena los pasos', 'verbose_name_plural': 'Temas de ordena los pasos'},
        ),
        migrations.RemoveField(
            model_name='ordenapasos',
            name='tiempo_limite_segundos',
        ),
        migrations.AlterField(
            model_name='pasoordenapasos',
            name='juego',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pasos_legacy', to='core.ordenapasos'),
        ),
        migrations.CreateModel(
            name='EtapaOrdenaPasos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('tiempo_limite_segundos', models.PositiveIntegerField(default=60)),
                ('activo', models.BooleanField(default=True)),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='core.ordenapasos')),
            ],
            options={
                'verbose_name': 'Etapa de ordena los pasos',
                'verbose_name_plural': 'Etapas de ordena los pasos',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.AddField(
            model_name='pasoordenapasos',
            name='etapa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pasos', to='core.etapaordenapasos'),
        ),
        migrations.CreateModel(
            name='ResultadoOrdenaPasos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('puntaje', models.PositiveIntegerField()),
                ('total_pasos', models.PositiveIntegerField()),
                ('porcentaje', models.PositiveIntegerField()),
                ('tiempo_total_segundos', models.PositiveIntegerField(default=0)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='core.ordenapasos')),
            ],
            options={
                'verbose_name': 'Resultado de ordena los pasos',
                'verbose_name_plural': 'Resultados de ordena los pasos',
                'ordering': ['-porcentaje', '-puntaje', 'tiempo_total_segundos', 'fecha'],
            },
        ),
    ]
