# Generated by Django 6.0.3 on 2026-03-26 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_ordenapasos_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasoordenapasos',
            name='juego',
        ),
        migrations.AlterField(
            model_name='pasoordenapasos',
            name='etapa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos', to='core.etapaordenapasos'),
        ),
    ]
