# Generated by Django 6.0.3 on 2026-03-26 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_pasoordenapasos_juego_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenapasos',
            name='material_recomendado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temas_ordena_pasos', to='core.material'),
        ),
        migrations.AddField(
            model_name='ordenapasos',
            name='porcentaje_minimo_recomendacion',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='ordenapasos',
            name='video_recomendado_url',
            field=models.URLField(blank=True),
        ),
    ]
