# Generated by Django 6.0.3 on 2026-03-27 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_ordenapasos_material_recomendado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trivia',
            name='material_recomendado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trivias_recomendadas', to='core.material'),
        ),
        migrations.AddField(
            model_name='trivia',
            name='porcentaje_minimo_recomendacion',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='trivia',
            name='video_recomendado_url',
            field=models.URLField(blank=True),
        ),
    ]
