# Generated by Django 6.0.3 on 2026-03-27 22:20

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_trivia_material_recomendado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponenteInteractivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('html', models.TextField(blank=True)),
                ('css', models.TextField(blank=True)),
                ('javascript', models.TextField(blank=True)),
                ('alto_iframe', models.PositiveIntegerField(default=500)),
                ('publicado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Componente interactivo',
                'verbose_name_plural': 'Componentes interactivos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='BloquePagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('titulo', 'Título'), ('texto', 'Texto'), ('imagen', 'Imagen'), ('galeria', 'Galería'), ('video', 'Video'), ('materiales', 'Materiales'), ('separador', 'Separador'), ('interactivo', 'Interactivo')], max_length=20)),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('subtitulo', models.CharField(blank=True, max_length=250)),
                ('contenido', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Contenido del bloque')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='bloques_pagina/')),
                ('video_url', models.URLField(blank=True)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
                ('materiales', models.ManyToManyField(blank=True, related_name='bloques_pagina', to='core.material')),
                ('componente_interactivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bloques_usados', to='core.componenteinteractivo')),
            ],
            options={
                'verbose_name': 'Bloque de página',
                'verbose_name_plural': 'Bloques de página',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ImagenBloquePagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='bloques_galeria/')),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('texto_alternativo', models.CharField(blank=True, max_length=200)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('bloque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_galeria', to='core.bloquepagina')),
            ],
            options={
                'verbose_name': 'Imagen de galería',
                'verbose_name_plural': 'Imágenes de galería',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('contenido', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Contenido')),
                ('imagen_portada', models.ImageField(blank=True, null=True, upload_to='paginas/')),
                ('orden', models.PositiveIntegerField(default=1)),
                ('publicado', models.BooleanField(default=True)),
                ('mostrar_en_menu', models.BooleanField(default=False)),
                ('materiales', models.ManyToManyField(blank=True, related_name='paginas', to='core.material')),
                ('pagina_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subpaginas', to='core.pagina', verbose_name='Página padre')),
            ],
            options={
                'verbose_name': 'Página',
                'verbose_name_plural': 'Páginas',
                'ordering': ['orden', 'titulo'],
            },
        ),
        migrations.AddField(
            model_name='bloquepagina',
            name='pagina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='core.pagina'),
        ),
    ]
