# Generated by Django 6.0.3 on 2026-03-28 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_componenteinteractivo_bloquepagina_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EligeCamino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Juego elige el camino',
                'verbose_name_plural': 'Juegos elige el camino',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='RuletaDesafio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ruleta de desafío',
                'verbose_name_plural': 'Ruletas de desafíos',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='EscenaCamino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('texto', models.TextField()),
                ('orden', models.PositiveIntegerField(default=1)),
                ('es_inicio', models.BooleanField(default=False)),
                ('es_final', models.BooleanField(default=False)),
                ('tipo_final', models.CharField(blank=True, choices=[('bueno', 'Bueno'), ('neutro', 'Neutro'), ('malo', 'Malo')], max_length=10)),
                ('video_recomendado_url', models.URLField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('camino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escenas', to='core.eligecamino')),
                ('material_recomendado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escenas_camino_recomendadas', to='core.material')),
            ],
            options={
                'verbose_name': 'Escena de camino',
                'verbose_name_plural': 'Escenas de camino',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OpcionEscenaCamino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_opcion', models.CharField(max_length=300)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
                ('escena_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones_que_llegan', to='core.escenacamino')),
                ('escena_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='core.escenacamino')),
            ],
            options={
                'verbose_name': 'Opción de escena',
                'verbose_name_plural': 'Opciones de escena',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SectorRuleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=300)),
                ('tipo', models.CharField(choices=[('prenda_castigo', 'Prenda o castigo'), ('buena_accion', 'Buena acción diaria')], default='prenda_castigo', max_length=20)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
                ('ruleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectores', to='core.ruletadesafio')),
            ],
            options={
                'verbose_name': 'Sector de ruleta',
                'verbose_name_plural': 'Sectores de ruleta',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
