# Generated by Django 6.0.3 on 2026-03-29 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_eligecamino_ruletadesafio_escenacamino_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='seccion',
        ),
        migrations.CreateModel(
            name='CategoriaBiblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='core.categoriabiblioteca', verbose_name='Categoría padre')),
            ],
            options={
                'verbose_name': 'Categoría de biblioteca',
                'verbose_name_plural': 'Categorías de biblioteca',
                'ordering': ['orden', 'nombre', 'id'],
            },
        ),
        migrations.AddField(
            model_name='material',
            name='categoria_biblioteca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiales', to='core.categoriabiblioteca', verbose_name='Categoría de biblioteca'),
        ),
    ]
