# Generated by Django 6.0.3 on 2026-03-29 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_material_seccion_categoriabiblioteca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='mostrar_en_biblioteca',
            field=models.BooleanField(default=True, verbose_name='Mostrar en biblioteca'),
        ),
        migrations.AlterField(
            model_name='material',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
