# Generated by Django 6.0.3 on 2026-04-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_material_mostrar_en_biblioteca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='trivias/preguntas/'),
        ),
    ]
