# Generated by Django 6.0.3 on 2026-09-13 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('publicado', models.BooleanField(default=False)),
                ('formadores', models.ManyToManyField(blank=True, related_name='cursos_asignados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='aula.curso')),
            ],
            options={
                'ordering': ['orden', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('texto', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True, help_text='Enlace HTTPS al video educativo.')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('publicada', models.BooleanField(default=False)),
                ('obligatoria', models.BooleanField(default=True)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecciones', to='aula.modulo')),
            ],
            options={
                'ordering': ['orden', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cursante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones_aula', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='aula.curso')),
                ('tutor', models.ForeignKey(blank=True, help_text='EDiFoS verifica la acreditación Scouter/Maestro Scout y el acuerdo del Jefe de Grupo.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tutorias_aula', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('curso', 'cursante'), name='aula_inscripcion_unica')],
            },
        ),
        migrations.CreateModel(
            name='Progreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completada_en', models.DateTimeField(auto_now_add=True)),
                ('cursante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aula.leccion')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('cursante', 'leccion'), name='aula_progreso_unico')],
            },
        ),
    ]
