# Generated by Django 6.0.3 on 2026-09-14 00:10

import aula.almacenamiento
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leccion',
            name='texto_enriquecido',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.CreateModel(
            name='RecursoLeccion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('documento', 'Documento'), ('video', 'Video'), ('imagen', 'Imagen')], max_length=12)),
                ('archivo', models.FileField(storage=aula.almacenamiento.privado, upload_to=aula.almacenamiento.ruta_archivo)),
                ('vista_pdf', models.FileField(blank=True, storage=aula.almacenamiento.privado, upload_to=aula.almacenamiento.ruta_archivo)),
                ('mime', models.CharField(max_length=100)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='aula.leccion')),
            ],
            options={
                'ordering': ['orden', 'creado'],
            },
        ),
    ]
