# Generated by Django 6.0.3 on 2026-09-14 02:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0002_leccion_texto_enriquecido_recursoleccion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='certificacion_configurada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='curso',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='horas',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='referencia_formacion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='curso',
            name='requiere_acta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='curso',
            name='responsable_certificados',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('participacion', 'Participación'), ('aprobacion', 'Participación y aprobación')], max_length=20)),
                ('datos', models.JSONField()),
                ('emitido', models.DateTimeField(auto_now_add=True)),
                ('revocado', models.BooleanField(default=False)),
                ('motivo_revocacion', models.TextField(blank=True)),
                ('fecha_revocacion', models.DateTimeField(null=True)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificados', to='aula.inscripcion')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('revocado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificados_revocados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CierreCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_certificado', models.CharField(max_length=200)),
                ('participacion_validada', models.BooleanField(default=False)),
                ('requisitos_validados', models.BooleanField(default=False)),
                ('aprobado', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('libro', models.CharField(blank=True, max_length=100)),
                ('acta', models.CharField(blank=True, max_length=100)),
                ('folio', models.CharField(blank=True, max_length=100)),
                ('fecha_acta', models.DateField(blank=True, null=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('inscripcion', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cierre', to='aula.inscripcion')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IntentoPrueba',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.PositiveIntegerField()),
                ('revision', models.PositiveIntegerField()),
                ('estructura', models.JSONField()),
                ('respuestas', models.JSONField(default=dict)),
                ('estado', models.CharField(choices=[('abierto', 'En curso'), ('pendiente', 'Por corregir'), ('corregido', 'Corregido')], default='abierto', max_length=16)),
                ('puntaje', models.PositiveIntegerField(null=True)),
                ('minimo', models.PositiveIntegerField()),
                ('aprobado', models.BooleanField(default=False)),
                ('iniciado', models.DateTimeField(auto_now_add=True)),
                ('entregado', models.DateTimeField(null=True)),
                ('cursante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-iniciado'],
            },
        ),
        migrations.CreateModel(
            name='CorreccionPrueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.PositiveIntegerField()),
                ('devolucion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('intento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correcciones', to='aula.intentoprueba')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos', models.JSONField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cierre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial', to='aula.cierrecurso')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('trivia', 'Trivia / quiz'), ('ordenar', 'Ordenar pasos'), ('memoria', 'Relacionar parejas'), ('palabra', 'Palabra secreta'), ('camino', 'Elegir un camino'), ('ruleta', 'Ruleta de retos'), ('rompecabezas', 'Rompecabezas')], max_length=20)),
                ('instrucciones', models.TextField(blank=True)),
                ('minimo', models.PositiveIntegerField(default=70)),
                ('max_intentos', models.PositiveIntegerField(default=3)),
                ('obligatoria', models.BooleanField(default=True)),
                ('origen', models.CharField(blank=True, max_length=250)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('contenido', models.JSONField(default=dict)),
                ('leccion', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='prueba', to='aula.leccion')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPrueba',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('texto', models.TextField()),
                ('opciones', models.JSONField(default=list)),
                ('respuesta', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
                ('prueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='aula.prueba')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.AddField(
            model_name='intentoprueba',
            name='prueba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intentos', to='aula.prueba'),
        ),
        migrations.AddConstraint(
            model_name='intentoprueba',
            constraint=models.UniqueConstraint(fields=('prueba', 'cursante', 'numero'), name='aula_intento_numero_unico'),
        ),
    ]
