# Generated by Django 6.0.3 on 2026-09-14 03:24

import aula.almacenamiento
import aula.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0003_curso_certificacion_configurada_curso_fecha_fin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemaForo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160)),
                ('texto', models.TextField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now_add=True)),
                ('resuelto', models.BooleanField(default=False)),
                ('cerrado', models.BooleanField(default=False)),
                ('oculto', models.BooleanField(default=False)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='temas_foro', to='aula.curso')),
            ],
            options={
                'ordering': ['-actualizado', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaForo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('oculto', models.BooleanField(default=False)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respuestas', to='aula.temaforo')),
            ],
            options={
                'ordering': ['creado', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='DisenoCertificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('participacion', 'Participación'), ('aprobacion', 'Participación y aprobación')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fondo', models.FileField(blank=True, storage=aula.almacenamiento.privado, upload_to=aula.models.ruta_plantilla)),
                ('configuracion', models.JSONField(default=dict)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aula.curso')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('curso', 'tipo'), name='aula_diseno_certificado_unico')],
            },
        ),
        migrations.CreateModel(
            name='PermisoFormador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responder_foro', models.BooleanField(default=True, verbose_name='Participar en el foro')),
                ('moderar_foro', models.BooleanField(default=False, verbose_name='Moderar el foro')),
                ('ver_seguimiento', models.BooleanField(default=True, verbose_name='Ver seguimiento de cursantes')),
                ('corregir', models.BooleanField(default=True, verbose_name='Corregir evaluaciones')),
                ('validar', models.BooleanField(default=False, verbose_name='Validar aprobación y registrar actas')),
                ('emitir', models.BooleanField(default=False, verbose_name='Emitir, descargar y revocar certificados')),
                ('disenar', models.BooleanField(default=False, verbose_name='Editar plantillas de certificados')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aula.curso')),
                ('formador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'permisos de un formador',
                'verbose_name_plural': 'permisos de formadores por curso',
                'constraints': [models.UniqueConstraint(fields=('curso', 'formador'), name='aula_permiso_formador_unico')],
            },
        ),
    ]
