# Generated by Django 6.0.3 on 2026-09-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0004_temaforo_respuestaforo_disenocertificado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leccion',
            name='eliminada',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
