# Generated by Django 6.0.8 on 2026-09-17 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0005_leccion_eliminada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(blank=True, max_length=16, verbose_name='DNI')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('direccion', models.CharField(blank=True, max_length=250, verbose_name='Dirección')),
                ('localidad', models.CharField(blank=True, max_length=150, verbose_name='Localidad')),
                ('codigo_postal', models.CharField(blank=True, max_length=20, verbose_name='Código postal')),
                ('telefono', models.CharField(blank=True, max_length=40, verbose_name='Teléfono')),
                ('estado_civil', models.CharField(blank=True, max_length=80, verbose_name='Estado civil')),
                ('cantidad_hijos', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Cantidad de hijos')),
                ('profesion', models.CharField(blank=True, max_length=200, verbose_name='Profesión / trabajo')),
                ('asociacion', models.CharField(blank=True, max_length=200, verbose_name='Asociación')),
                ('grupo', models.CharField(blank=True, max_length=200, verbose_name='Grupo al que pertenecés')),
                ('fecha_ingreso_grupo', models.DateField(blank=True, null=True, verbose_name='Fecha de ingreso al grupo')),
                ('fecha_ingreso_movimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de ingreso al Movimiento Scout')),
                ('sacramentos', models.CharField(blank=True, max_length=250, verbose_name='Sacramentos')),
                ('fecha_promesa', models.DateField(blank=True, null=True, verbose_name='Fecha de promesa')),
                ('cargo', models.CharField(blank=True, max_length=200, verbose_name='Cargo que desempeñás')),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_aula', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil privado',
                'verbose_name_plural': 'perfiles privados',
            },
        ),
    ]
