# Generated by Django 6.0.8 on 2026-09-19 00:01

import aula.almacenamiento
import aula.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0006_perfil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='cambiar_clave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, storage=aula.almacenamiento.privado, upload_to=aula.models.ruta_foto, verbose_name='Foto de perfil'),
        ),
        migrations.CreateModel(
            name='AccesoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitado', models.BooleanField(default=True)),
                ('dias', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Días desde el primer ingreso')),
                ('inicio', models.DateTimeField(blank=True, null=True, verbose_name='Inicio del acceso')),
                ('fin', models.DateTimeField(blank=True, null=True, verbose_name='Fin del acceso')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos', to='aula.curso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos_aula', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'acceso al curso',
                'verbose_name_plural': 'accesos por fechas',
                'constraints': [models.UniqueConstraint(fields=('curso', 'usuario'), name='aula_acceso_unico')],
            },
        ),
    ]
