# Generated by Django 6.0.8 on 2026-09-19 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0007_perfil_cambiar_clave_perfil_foto_accesocurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='avatar',
            field=models.CharField(blank=True, choices=[('', 'Mi foto o mis iniciales'), ('brujula', '🧭 Brújula'), ('carpa', '⛺ Carpa'), ('montana', '🏔️ Montaña'), ('arbol', '🌳 Árbol'), ('fogata', '🔥 Fogata'), ('estrella', '⭐ Estrella'), ('lobo', '🐺 Lobo')], max_length=20, verbose_name='Elegir avatar'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='compartir_foto',
            field=models.BooleanField(default=False, verbose_name='Mostrar mi foto a los compañeros y formadores de mis cursos'),
        ),
    ]
